### ISSUE TITLE
hydra.errors.InstantiationException: Error in call to target 'training.trainer.Trainer'

### ISSUE THREAD

**Issue by zsz00** [facebookresearch/sam2#415]
I upgraded to tensordict==0.6 and pytorch==2.5, but meet this error :
[rank0]: hydra.errors.InstantiationException: Error in call to target 'training.trainer.Trainer':
[rank0]: InstantiationException("Error locating target 'training.dataset.vos_dataset.VOSDataset', set env var HYDRA_FULL_ERROR=1 to see chained exception.\nfull_key: data.train.datasets[0].dataset.datasets0")
[rank0]: full_key: trainer

**Comment by bhack** [comment]
Is this the full stacktrace? Probably the real issue is earlier in the stacktrace.

**Comment by zsz00** [comment]
I fixed it. This error has nothing to do with the tensordict version. It's because the installed pytorch is different from the cuda version of torchvision. I also met with similar error hydra. Errors. InstantiationException: Error in call to target 'training.utils.checkpoint_utils.load_checkpoint_and_apply_kernels':

KeyError("filename 'storages' not found")

full_key: checkpoint.model_weight_initializer.state_dict

This is because there is a problem with the checkpoint file I gave, but the error is not clear because of hydra.

**Comment by williamwenlma** [comment]
Hi, I use torch==2.7.1, torchvision==0.22.1 + cuda118 and tensordict==0.8.3, try both windows and linux but still show this error

Raw dataset length = 0
[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 92, in _call_target
[rank0]:     return _target_(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\dataset\sam2_datasets.py", line 120, in __init__
[rank0]:     dataset_prob = torch.tensor([d_len / total_len for d_len in dataset_lens])
[rank0]:                                  ~~~~~~^~~~~~~~~~~
[rank0]: ZeroDivisionError: division by zero

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 92, in _call_target
[rank0]:     return _target_(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\trainer.py", line 211, in __init__
[rank0]:     self._setup_dataloaders()
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\trainer.py", line 525, in _setup_dataloaders
[rank0]:     self.train_dataset = instantiate(self.data_conf.train)
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
[rank0]:     return instantiate_node(
[rank0]:            ^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node
[rank0]:     return _call_target(_target_, partial, args, kwargs, full_key)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target
[rank0]:     raise InstantiationException(msg) from e
[rank0]: hydra.errors.InstantiationException: Error in call to target 'training.dataset.sam2_datasets.TorchTrainMixedDataset':
[rank0]: ZeroDivisionError('division by zero')
[rank0]: full_key: data.train

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\train.py", line 270, in <module>
[rank0]:     main(args)
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\train.py", line 240, in main
[rank0]:     single_node_runner(cfg, main_port)
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\train.py", line 53, in single_node_runner
[rank0]:     single_proc_run(local_rank=0, main_port=main_port, cfg=cfg, world_size=num_proc)
[rank0]:   File "D:\cjfai\sam2-oai\sam2\training\train.py", line 40, in single_proc_run
[rank0]:     trainer = instantiate(cfg.trainer, _recursive_=False)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
[rank0]:     return instantiate_node(
[rank0]:            ^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node
[rank0]:     return _call_target(_target_, partial, args, kwargs, full_key)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "D:\cjfai\sam2-oai\sam2-venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target
[rank0]:     raise InstantiationException(msg) from e
[rank0]: hydra.errors.InstantiationException: Error in call to target 'training.trainer.Trainer':
[rank0]: InstantiationException("Error in call to target 'training.dataset.sam2_datasets.TorchTrainMixedDataset':\nZeroDivisionError('division by zero')\nfull_key: data.train")
[rank0]: full_key: trainer

**Comment by sipie800** [comment]
+1

**Comment by sipie800** [comment]
hydra is such an ugly kpi-driving thing
